CREATE TABLE CUSTOMER (
    CUST_ID VARCHAR(3) PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20),
    AREA VARCHAR(10),
    PHONE VARCHAR(15),
    CHECK (CUST_ID LIKE 'A%')
);

INSERT INTO CUSTOMER (CUST_ID, FNAME, LNAME, AREA, PHONE)
VALUES
('A01', 'Ivan', 'Bayross', 'SA', '6125467'),
('A02', 'Vandana', 'Saiteal', 'MU', '5560379'),
('A03', 'Pramada', 'Jauguste', 'DA', '4560389'),
('A04', 'Basu', 'Navindi', 'BA', '6125401'),
('A05', 'Ravi', 'Shreedhar', 'NA', NULL),
('A06', 'Rukmini', NULL, 'GH', '5125274');

CREATE TABLE MOVIE (
    MV_NO INT PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    STAR VARCHAR(20) NOT NULL,
    PRICE DECIMAL(8,2) NOT NULL
);

INSERT INTO MOVIE (MV_NO, TITLE, TYPE, STAR, PRICE)
VALUES
(1, 'Bloody', 'Action', 'JC', 181),
(2, 'The Firm', 'Thriller', 'TC', 200),
(3, 'Pretty Woman', 'Romance', 'RG', 151),
(4, 'Home Alone', 'Comedy', 'MC', 150),
(5, 'The Fugitive', 'Thriller', 'MF', 200),
(6, 'Coma', 'Suspense', 'MD', 100),
(7, 'Dracula', 'Horror', 'GO', 150),
(8, 'Quick Change', 'Comedy', 'BM', 100),
(9, 'Gone with the Wind', 'Action', 'CB', 200),
(10, 'Carry on Doctor', 'Comedy', 'LP', 100);

CREATE TABLE INVOICE (
    INV_NO VARCHAR(3) PRIMARY KEY,
    MV_NO INT,
    CUST_ID VARCHAR(3),
    ISSUE_DATE DATE NOT NULL,
    RETURN_DATE DATE NOT NULL,
    CHECK (INV_NO LIKE 'I%'),
    FOREIGN KEY (MV_NO) REFERENCES MOVIE(MV_NO),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);

INSERT INTO INVOICE
(INV_NO, MV_NO, CUST_ID, ISSUE_DATE, RETURN_DATE)
VALUES
('I01', 4, 'A01', '1993-07-23', '1993-07-25'),
('I02', 3, 'A02', '1993-08-12', '1993-08-15'),
('I03', 1, 'A02', '1993-08-15', '1993-08-18'),
('I04', 6, 'A03', '1993-09-10', '1993-09-13'),
('I05', 7, 'A04', '1993-08-05', '1993-08-08'),
('I06', 2, 'A06', '1993-09-18', '1993-09-21'),
('I07', 9, 'A05', '1993-07-07', '1993-07-10'),
('I08', 9, 'A01', '1993-08-11', '1993-08-14'),
('I09', 5, 'A03', '1993-07-06', '1993-07-09'),
('I10', 8, 'A06', '1993-09-03', '1993-09-06');

SELECT C.FNAME, C.LNAME, I.MV_NO
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID;


SELECT M.MV_NO, M.TITLE
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID
JOIN MOVIE M
ON I.MV_NO = M.MV_NO
WHERE C.FNAME = 'Ivan';


SELECT M.TITLE, I.CUST_ID, I.MV_NO
FROM MOVIE M
JOIN INVOICE I
ON M.MV_NO = I.MV_NO;

SELECT M.TITLE, M.TYPE
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID
JOIN MOVIE M
ON I.MV_NO = M.MV_NO
WHERE C.FNAME = 'Vandana';


SELECT DISTINCT C.FNAME, C.LNAME
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID
JOIN MOVIE M
ON I.MV_NO = M.MV_NO
WHERE M.TYPE = 'Action';



SELECT
    CONCAT(
        'The movie taken by ',
        C.FNAME,
        ' ',
        COALESCE(C.LNAME, ''),
        ' is ',
        M.TITLE
    ) AS MOVIE_DETAILS
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID
JOIN MOVIE M
ON I.MV_NO = M.MV_NO
WHERE M.MV_NO >= 3;

SELECT C.*
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID
WHERE I.INV_NO = 'I10';

SELECT DISTINCT
    C.FNAME,
    C.LNAME,
    C.PHONE,
    C.AREA
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID
WHERE I.ISSUE_DATE < '1993-08-01';

SELECT
    C.FNAME,
    M.MV_NO,
    M.TITLE
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID
JOIN MOVIE M
ON I.MV_NO = M.MV_NO
WHERE C.FNAME IN ('Ivan','Vandana','Ravi');


SELECT
    M.MV_NO,
    M.TITLE
FROM MOVIE M
JOIN INVOICE I
ON M.MV_NO = I.MV_NO;

SELECT
    M.TYPE,
    M.MV_NO
FROM MOVIE M
JOIN INVOICE I
ON M.MV_NO = I.MV_NO
WHERE I.CUST_ID IN ('A01', 'A02');

SELECT
I.CUST_ID
FROM MOVIE M
JOIN INVOICE I
ON M.MV_NO = I.MV_NO
WHERE M.STAR = 'TC';

SELECT DISTINCT
    C.FNAME,
    C.LNAME
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUST_ID = I.CUST_ID;

SELECT MV_NO
FROM MOVIE
WHERE MV_NO NOT IN (
SELECT MV_NO
FROM INVOICE
);